<?php

namespace Laravel\Cashier\Tests\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Laravel\Cashier\Cashier;
use Laravel\Cashier\Tests\Fixtures\User;

class RedeemedCouponFactory extends Factory
{
    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return string
     */
    public function modelName()
    {
        return Cashier::$redeemedCouponModel;
    }

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => 'Test redemeed coupon',
            'model_type' => Cashier::$subscriptionModel,
            'model_id' => 1,
            'owner_type' => User::class,
            'owner_id' => 1,
            'times_left' => 1,
        ];
    }
}
