<?php

namespace Laravel\Cashier\Tests\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Laravel\Cashier\Cashier;
use Laravel\Cashier\Tests\Fixtures\User;
use Mollie\Api\Types\RefundStatus;

class RefundFactory extends Factory
{
    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return string
     */
    public function modelName()
    {
        return Cashier::$refundModel;
    }

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'owner_id' => 1,
            'owner_type' => User::class,
            'original_order_id' => 1,
            'mollie_refund_id' => 're_dummy_refund_id',
            'mollie_refund_status' => RefundStatus::STATUS_PENDING,
        ];
    }
}
