name: tests

on:
    push:
    pull_request:
    schedule:
        - cron: '0 0 * * *'

jobs:
    tests:

        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                os: [ ubuntu-latest ]
                php: [8.3, 8.2, 8.1]
                laravel: [ 11.*, 10.* ]
                dependency-version: [ prefer-stable ]

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: curl, dom, intl, json, libxml, mbstring, openssl, zip
                  tools: composer:v2
                  coverage: xdebug

            - name: Install dependencies
              run: |
                  composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress

            - name: Execute tests
              run: vendor/bin/phpunit --coverage-text
